# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='ispublic',
            field=models.BooleanField(default=False),
        ),
    ]
