# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_ispublic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
