# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 03:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=500, null=True)),
                ('fly_title', models.CharField(blank=True, max_length=500, null=True)),
                ('alternativename', models.CharField(blank=True, max_length=500, null=True)),
                ('content_dirty', models.TextField(blank=True, null=True)),
                ('content_clean', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, max_length=500, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(editable=False, max_length=500)),
                ('spider', models.CharField(editable=False, max_length=500)),
                ('create_date', models.DateTimeField(editable=False)),
                ('project', models.CharField(editable=False, max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-source', 'category'],
            },
        ),
    ]
