# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economist', '0002_auto_20170406_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='alternativename',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='fly_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='project',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='spider',
            field=models.TextField(editable=False),
        ),
    ]
